spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

  devtools:
    restart:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true

keycloak:
  auth-server-url: http://localhost:8088

logging:
  level:
    tg.ngstars: DEBUG
    org.springframework.security: DEBUG
