<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/ma
         ven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>tg.ngstars</groupId>
    <artifactId>ng-fields-backend</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>shared-lib</module>
        <module>auth-service</module>
        <module>client-service</module>
        <module>gateway-service</module>
        <module>intervention-service</module>
        <module>media-service</module>
        <module>notification-service</module>
        <module>report-service</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <testcontainers.version>1.21.0</testcontainers.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${testcontainers.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>